name: Build Reports

on:
    push:
        branches: [main]
        paths:
            - '**.md'
            - '**.sh'
            - '**.yml'
            - '**/img/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"
            - name: Build PDFs
              run: |
                  npm ci
                  ./runner.sh 01
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: build

    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
            - name: Copy README
              run: |
                  mkdir build
                  cp LICENSE build/LICENSE
                  cp README.md build/README.md
            - name: Download a Build Artifact
              uses: actions/download-artifact@v3
              with:
                  name: build
                  path: build
            - name: List files
              working-directory: build
              run: |
                  sudo apt install -y tree
                  tree
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.2.2
              with:
                  branch: gh-pages
                  folder: build
                  clean: false
